kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  proxy-buffer-size: "16k"
  http2-max-field-size: "16k"
