kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  proxy-buffer-size: "16k"
  http2-max-field-size: "16k"
  #http2-max-header-size: "128k"
  #client-header-buffer-size: "16k"
  large-client-header-buffers: "4 16k"
